label:          Classification
data_directory: /Users/corey.adams/data/DUNE/pixsim_small/
train_file:     test.h5
test_file:      none
val_file:       test.h5
imgaes:         3
access_mode:    serial_access
dimension:      2
