label:          Classification
test_file:      none
images:         3
access_mode:    serial_access
dimension:      2
data_directory: /lus/grand/projects/datascience/cadams/datasets/DUNE/full_merged/
train_file:     pixsim_full_test.h5
val_file:       pixsim_full_val.h5
